name: Cliente Side Tools and Coverage

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send Client Side Tools and Coverage Results
        env:
          CODACY_PROJECT_TOKEN: {{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          gradle jacocoTestReport
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r lib/build/reports/jacoco/test/jacocoTestReport.xml
          docker run \
            --rm=true \
            -- env CODACY_CODE="$CODACY_CODE" \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume "$CODACY_CODE":"$CODACY_CODE" \
            --volume /tmp:/tmp \
            codacy/codacy-analysis-cli \
              analyze --tool spotbus --upload --project-token #{{ secrets.CODACY_PROJECT_TOKEN}} --max-allowed-issues 99999 --commit-uuid $GITHUB_SHA


